// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJbyKN_HLa4s__qa2-GS8tFjPOWBbyEc0',
    appId: '1:577388032723:web:09ca1e646522e7c4da5a26',
    messagingSenderId: '577388032723',
    projectId: 'kasiiot',
    authDomain: 'kasiiot.firebaseapp.com',
    databaseURL: 'https://kasiiot-default-rtdb.firebaseio.com',
    storageBucket: 'kasiiot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCriO5gDo_QIwoq86rOwn01OZW_sXZnL8',
    appId: '1:577388032723:android:cee6c8cb9ae66261da5a26',
    messagingSenderId: '577388032723',
    projectId: 'kasiiot',
    databaseURL: 'https://kasiiot-default-rtdb.firebaseio.com',
    storageBucket: 'kasiiot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ6a5HeT2Ap-19MYoJ_5DVdxGjFEFrWEg',
    appId: '1:577388032723:ios:903b269252b730c9da5a26',
    messagingSenderId: '577388032723',
    projectId: 'kasiiot',
    databaseURL: 'https://kasiiot-default-rtdb.firebaseio.com',
    storageBucket: 'kasiiot.appspot.com',
    iosClientId: '577388032723-mn6m86btv6ho20e2kr1j0sn3uieuq4j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.betaFlex',
  );
}
